[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run temporal:server:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "7233"
TEMPORAL_UI_PORT = "8080"
NODE_ENV = "production"